clone:
  git: 
    image: plugins/git
pipeline:
  build:
    image: istio/ci:go1.11-bazelisk-clang8-cmake3.8.0
    commands:
      # - make lint
      - make build
      - make test
    environment:
        BAZEL_BUILD_ARGS: "--local_ram_resources=12288 --local_cpu_resources=8 --verbose_failures --test_env=ENVOY_IP_TEST_VERSIONS=v4only --test_output=all"
  
  test:
    image: istio/ci:go1.11-bazelisk-clang8-cmake3.8.0
    commands:
      - make test_envoy
    environment:
      BAZEL_BUILD_ARGS: "--local_ram_resources=12288 --local_cpu_resources=8 --verbose_failures --test_env=ENVOY_IP_TEST_VERSIONS=v4only --test_output=all"
  
