clone:
  git: 
    image: plugins/git
pipeline:
  build:
    image: costinm/proxyv2:master-latest-daily
    commands:
      - id
      - env
      - sudo chown -R circleci /drone/src
      - HOME=/drone/src make build_envoy
  test:
    image: costinm/proxyv2:master-latest-daily
    commands:
      - id
      - env
      - sudo chown -R circleci /drone/src
      - HOME=/drone/src make test_envoy


